// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe_iXSeP1R4k4FXT3QmtA-vyH_X2XS_bA',
    appId: '1:628795061976:web:c26b472445c0ce5fe909ad',
    messagingSenderId: '628795061976',
    projectId: 'bootcamp7-c67f5',
    authDomain: 'bootcamp7-c67f5.firebaseapp.com',
    storageBucket: 'bootcamp7-c67f5.appspot.com',
    measurementId: 'G-HSVH7D96MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv6UEKw5ueEKj9j-SCaoVAD1rfJAw78_o',
    appId: '1:628795061976:android:087fdf5ce2c69583e909ad',
    messagingSenderId: '628795061976',
    projectId: 'bootcamp7-c67f5',
    storageBucket: 'bootcamp7-c67f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0fJdvHyyF24pQ4LGxAVnyEzf_--qisYw',
    appId: '1:628795061976:ios:3d714ba3a0e0c1b5e909ad',
    messagingSenderId: '628795061976',
    projectId: 'bootcamp7-c67f5',
    storageBucket: 'bootcamp7-c67f5.appspot.com',
    iosBundleId: 'com.example.bootcamp7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0fJdvHyyF24pQ4LGxAVnyEzf_--qisYw',
    appId: '1:628795061976:ios:3d714ba3a0e0c1b5e909ad',
    messagingSenderId: '628795061976',
    projectId: 'bootcamp7-c67f5',
    storageBucket: 'bootcamp7-c67f5.appspot.com',
    iosBundleId: 'com.example.bootcamp7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe_iXSeP1R4k4FXT3QmtA-vyH_X2XS_bA',
    appId: '1:628795061976:web:c43f55c5e4449d83e909ad',
    messagingSenderId: '628795061976',
    projectId: 'bootcamp7-c67f5',
    authDomain: 'bootcamp7-c67f5.firebaseapp.com',
    storageBucket: 'bootcamp7-c67f5.appspot.com',
    measurementId: 'G-LHZGMZ5J6C',
  );
}
